version: "3.2"

services:
  nginx:
    image: nginx:latest
    env_file: ./env
    volumes:
    - ./site.template:/etc/nginx/conf.d/site.template:ro
    - ./data/wp:/var/www/html:rw
    - ./site_nginx.conf:/etc/nginx/nginx.conf
    #ports:
    #- "80:80"
    command: /bin/bash -c "envsubst '$$NGINX_HOST,$$NGINX_PORT' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - memcached
      - wordpress
    networks:
      ${TRAEFIK_NETWORK}:
      internal:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: nginx
        traefik.frontend.rule: "Host:${NGINX_HOST},www.${NGINX_HOST}"
        traefik.docker.network: infra-traefik_public
        traefik.port: '80'
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s

  memcached:
    image: amd64/memcached
    labels:
      - traefik.enable=false
    networks:
      internal:

  wordpress:
    image: ptsiampas/dexs-wp:4.9.8-php7.1-fpm
    build:
      context: builds/php7-fpm
    secrets:
      - source: ${CONTAINER_NAME}-mysql-root-pass
      - source: ${CONTAINER_NAME}-wp-user
      - source: ${CONTAINER_NAME}-wp-user-pass

    depends_on:
      - mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER_FILE=/run/secrets/${CONTAINER_NAME}-wp-user
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/${CONTAINER_NAME}-wp-user-pass
      - afinity:container==nginx
    labels:
      traefik.enable: "false"
    networks:
      internal:
    volumes:
      - ./data/wp:/var/www/html:rw

  mysql:
    image: mysql:5.7.21
    secrets:
      - ${CONTAINER_NAME}-mysql-root-pass
      - ${CONTAINER_NAME}-wp-user
      - ${CONTAINER_NAME}-wp-user-pass
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/${CONTAINER_NAME}-mysql-root-pass
      - MYSQL_USER_FILE=/run/secrets/${CONTAINER_NAME}-wp-user
      - MYSQL_PASSWORD_FILE=/run/secrets/${CONTAINER_NAME}wp-user-pass
      - afinity:container!=wordpress
    labels:
      traefik.enable: "false"
    networks:
      internal:
    volumes:
      - ./data/db:/var/lib/mysql:rw
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  ${TRAEFIK_NETWORK}:
    external: true
  internal:
    driver: overlay
    attachable: true